### ISSUE TITLE
Translation:./src/cmd/go/doc.go

### ISSUE THREAD

**Issue by inatus** [gophersjp/go#12]
https://code.google.com/p/go/source/browse/src/cmd/go/doc.go?r=c4d996668981f0bd23d3a6be0fff72d09334b380
時間かかるかもですが頑張ってこれやります。

**Comment by atotto** [comment]
これは大物ですね。

**Comment by inatus** [comment]
時間がかかってしまいすみません。
一旦ざっと訳しました。
これから推敲に移ります。

**Comment by inatus** [comment]
遅くなりましたが完了しましたのでクローズします。

**Comment by atotto** [comment]
ありがとうございます！！

読み応えありますね http://godoc.org/github.com/gophersjp/go/src/cmd/go

**Comment by inatus** [comment]
段落内の改行は半角スペースに変換されてしまうのですね。段落内の改行を削除しました。また、全角文字だと見出し表示ができないようです。別途Issueに上げておきます。
