### ISSUE TITLE
src/pkgディレクトリ以下はgodoc.orgで表示されない

### ISSUE THREAD

**Issue by atotto** [gophersjp/go#17]
godoc.orgの制約ですね。goリポジトリのミラーとして判定されるようです。

https://github.com/garyburd/gddo/blob/master/gddo-server/crawl.go#L52

**Comment by atotto** [comment]
というわけで、 http://godocjp.herokuapp.com/ に自動デプロイするようにしてみたんですが、どうでしょう。
まだ世間に広めるにはあまりにも英語ですが・・・

**Comment by inatus** [comment]
おお、すごい！
さすがです！

もう少し翻訳が進んだらTwitterあたりでアナウンス（？）しましょうか。

**Comment by inatus** [comment]
Herokuの無料枠って実際どのぐらいいけるのかよくわかってないのですが、
さしあたってはこれで運用して、パフォーマンス足りなくなったらまた考えれば良いと思います。

**Comment by atotto** [comment]
> herokuの無料枠

わたしもよくわかってません（^^;
ひとまず様子を見つつですね。。

**Comment by atotto** [comment]
このチケットはひとまずcloseします。
