### ISSUE TITLE
./doc/docs.html

### ISSUE THREAD

**Issue by inatus** [gophersjp/go#18]
やります。

翻訳対象：
https://code.google.com/p/go/source/browse/doc/docs.html

**Comment by atotto** [comment]
おお、いいですね！

一応 https://github.com/gophersjp/go/blob/master/doc/root.html の上部にあるように：

```
<!--
本ドキュメントは以下のドキュメントを翻訳しています: https://code.google.com/p/go/source/browse/doc/root.html?name=default&r=5ffdb9cc0bfe719d18eef4a44a85711d521995fa
-->
```

をコメントアウトで構わないので追加しておいてくださいなー。

**Comment by inatus** [comment]
翻訳元ドキュメント情報追加してpushしました。
Closeします。
