### ISSUE TITLE
tipで更新されたドキュメントがないかをチェックできるようにする

### ISSUE THREAD

**Issue by atotto** [gophersjp/go#19]
翻訳したものがgoのtipで更新されてないかどうかチェックするものが必要なので作ります。

wikiにちょっとメモしています。

**Comment by inatus** [comment]
いいですね。
マストな機能だと思います。

**Comment by atotto** [comment]
作ってみました
http://godocjp.herokuapp.com/status/translate.html

ざっと説明すると：
- go1.2に対してどうなってるか
- tipに対してどうなってるか
  の表をだしてます。

なにかエラーが出てますが気にしないでください。あとで修正します・・・

リポジトリはとりあえず https://github.com/atotto/gophersjp-go-util に作ってみました。
気が向いたらどこかにまとめようかと思ったりなかったり。

**Comment by atotto** [comment]
どうやらdrone.ioのMercurialのバージョンが古くてまともに動いてないようです。。

```
$ hg version
Mercurial Distributed SCM (version 2.0.2)
```

対策を考えます。

**Comment by inatus** [comment]
おお、仕事早いですね。
素晴らしいです。。。

**Comment by atotto** [comment]
http://godocjp.herokuapp.com/status/translate.html
正確に表示されるようになりました。

手元の環境で再現しなかったので苦労しました・・・。
結局バージョンが問題ではなく、hg特有のlog表示の振る舞いに振り回されました。
- ["hg log" にファイル名を指定するなら "-k" で](http://d.hatena.ne.jp/flying-foozy/20100429/1272528071)
- https://groups.google.com/forum/#!topic/mercurial-ja/2coBla1sqNU

というわけで、closeしますー。
