### ISSUE TITLE
翻訳辞書の作成

### ISSUE THREAD

**Issue by inatus** [gophersjp/go#24]
翻訳対象ドキュメントもグッと増えたのでこれからどんどんと協力者を募っていきたいところですね！
そこでそろそろ翻訳辞書を作ったほうが良いと思い、ドラフトを作ってみました。

https://github.com/gophersjp/go/wiki/%E7%BF%BB%E8%A8%B3%E8%BE%9E%E6%9B%B8

いくつか候補が出せそうな語句（gotoutine・ゴルーチン、インタフェース・インタフェイス・インターフェイスなど）については議論したほうがいいですね。
ですので、
- 語句の追加については随時行う
- 議論が必要そうなものについては気づいた人がここで提案する

というのはどうでしょうか。

**Comment by atotto** [comment]
ありがとうございます！
いいと思います。

さっそくですが、
goroutineは、提案のままgoroutineでいいかなと思います。
interfaceは、structがstructであれば typeとしてのinterfaceもそのままの方がいいかもしれません。一般的な意味としてはインタフェースでいいと思います。このあたり判断むずかしいですね。

**Comment by inatus** [comment]
コメントありがとうございます。

何をカタカナで表して、何を原文のままにするかですが、
他の言語のドキュメントを参考にして、ちょっと考えてみました。

他に知ってる言語がJavaしかないので、Javaを例に考えてみました。
http://docs.oracle.com/javase/jp/7/
- 言語構成上の概念：カタカナ（インタフェース、チャネルなど）
- 言語仕様のステートメント：原文（struct, defer, panicなど）
- 一般的な機能：カタカナ（プリント、ロギングなど）
- 関数・変数や固有名詞的に使われるもの：原文

例：
1. 型は構造体を表現することができます。structによって宣言します。
2. エラーが発生した際には、panicが呼び出されます。
3. print関数は引数を標準出力にプリントします。
4. GopherはGo言語のマスコットです。

上記の考え方から、goroutineはやはりゴルーチンと表記するのが妥当と考えます。goroutineについては固有名詞っぽく感じられこともありますが、言語構成上の概念ですし、そもそもcoroutineをもじったもので、これは一般的にコルーチンと訳されるのでゴルーチンとするのが良いと思いました。

それをもとに一度対訳表を直しましたが、いかがでしょうか。

panic, recoverは言語構成上の概念とも考えられますが、関数の名前にもなっているので微妙なところだと思います。

**Comment by atotto** [comment]
修正ありがとうございます。
ゴルーチンでOKです。

だいぶ固い感じもしますが、たぶんきちんと翻訳活動するとこんなもんなのだろうと思いますのでいいと思います。

**Comment by atotto** [comment]
concurrency 並行
parallelism 並列

を並べて追加しました

**Comment by inatus** [comment]
ご確認ありがとうございます。
それでは、これでいきましょう。

**Comment by inatus** [comment]
今後、訳し方の議論が必要になった時のために、このIssueは開いたままにしておきます。

**Comment by inatus** [comment]
わかりやすいように別issueを立ち上げたので、こちらはcloseします。
