### ISSUE TITLE
./doc/go1.3.html

### ISSUE THREAD

**Issue by taka011239** [gophersjp/go#32]
1.3リリースノート翻訳します！
link: https://code.google.com/p/go/source/browse/doc/go1.3.html

**Comment by inatus** [comment]
ありがとうございます！
よろしくお願いします。

**Comment by inatus** [comment]
ご対応いただきましてありがとうございました。
マージしました。

**Comment by atotto** [comment]
ありがとうございます。

http://godocjp.herokuapp.com/doc/go1.3 で閲覧できます！
