### ISSUE TITLE
mobile環境からの閲覧について

### ISSUE THREAD

**Issue by taka011239** [gophersjp/go#34]
iOSのsafariから閲覧したところ、スクロールが引っかかる感じでスムーズに動きません。モバイル環境からの閲覧も考慮すべきでは？

**Comment by atotto** [comment]
本家と同じものを使っているんですがねぇ・・なにが違うんでしょうか

**Comment by atotto** [comment]
調べてみると最新の code.google.com/p/go.tools/ を使うとこの挙動になるようです。というわけで本家にコミットしないとですね。

**Comment by taka011239** [comment]
本家はスムーズに動きますね。時間があるとき、調べておきます。

**Comment by taka011239** [comment]
調査してみました。Go1.3からgodoc.htmlの構成が大分変わっているようで(レスポンシブになってたり)、CSSの-webkit-overflow-scrollingプロパティを追加しないと慣性スクロールが有効にならないようです。

**Comment by atotto** [comment]
調査ありがとうございます。

ひとまず、 code.google.com/p/go.tools/ の開発でサイトが左右されるのはあまり好ましくないので、go1.2リリース時点での godoc を使うようにしました。

**Comment by atotto** [comment]
最新のgodocでは本件の問題は解消されていました。
この辺り https://code.google.com/p/go/source/detail?r=c60f58db34e9c3bfdab210d38b2b36e3e6974dd0&repo=tools&path=/godoc/static/godoc.html の修正かと思います。

というわけで、本件closeします。
