### ISSUE TITLE
ドメイン取得しました

### ISSUE THREAD

**Issue by atotto** [gophersjp/go#41]
ドキュメントの翻訳が進んできたこともあり、次のステップとしてドメインを取得して見栄えを良くしようと思います。

というか、勝手に取りました・・ golang-jp.org 

http://golang-jp.org/ で閲覧できます。
相変わらずherokuで動かしていますが、今のところ問題なさそうです。

**Comment by inatus** [comment]
おお、いいですね！
ありがとうございます！

**Comment by atotto** [comment]
明日の夜にでもtwitter上でアナウンスしちゃおうと思います。

まだ #15 が問題として残っていますが、そのうち修正しようと思います。

**Comment by atotto** [comment]
アナウンスしました〜

https://twitter.com/atotto/status/471616881216860160
https://groups.google.com/forum/#!topic/golang-nuts/1_OIsSkODJw

こちらはアナウンスしていただきました！
https://plus.google.com/117794583266583636239/posts/Rbpvu7mzMR7

ちなみに、Go Conference 2014 springに行かれる方いませんか？
http://connpass.com/event/6370/

私はあいにく都合が悪く参加できません。。だれかアナウンスしていただけると・・・

**Comment by inatus** [comment]
ありがとうございます！
私もリツイートしました。

gocon、私も参加できないんですよね。。。
うーん、残念です。
