### ISSUE TITLE
./doc/go1.3.html update

### ISSUE THREAD

**Issue by atotto** [gophersjp/go#44]
link: https://code.google.com/p/go/source/browse/doc/go1.3.html

昨日、若干更新しましたがまだ一部残ってます。だれか残りやりますか〜？
6/1に間に合わせたいなと思ってます。

**Comment by t-yuki** [comment]
やります。

**Comment by atotto** [comment]
お願いしますm(__)m

**Comment by atotto** [comment]
LGTM 

ありがとうございます！

**Comment by atotto** [comment]
まだしばらく変更がありそうなので、 issue/44 にブランチをつくりました。

**Comment by atotto** [comment]
go1.3がリリースされたので、本件クローズします。
