### ISSUE TITLE
Translation: ./src/cmd/prof/doc.go

### ISSUE THREAD

**Issue by masato-ka** [gophersjp/go#5]
翻訳対象
https://code.google.com/p/go/source/browse/src/cmd/prof/doc.go

**Comment by masato-ka** [comment]
To inutus
Please review me!
https://github.com/gophersjp/go/blob/master/src/cmd/prof/doc.go

**Comment by atotto** [comment]
To masato-ka

チェンジ番号を含むURL
https://code.google.com/p/go/source/browse/src/cmd/prof/doc.go?r=3633a89bb56d9276a9fe55435b849f931bfa6393
を文書最下部にいれといてください。

こんな感じで：

```
本ドキュメントは以下のドキュメントを翻訳しています:  https://code.google.com/p/go/source/browse/src/cmd/prof/doc.go?r=3633a89bb56d9276a9fe55435b849f931bfa6393

```

**Comment by inatus** [comment]
お疲れさまです。
レビュー完了してコミットしました。
Diff取って内容を確認してみて下さい。
