### ISSUE TITLE
./src/pkg/os/doc.go

### ISSUE THREAD

**Issue by ucho** [gophersjp/go#51]
link: https://code.google.com/p/go/source/browse/src/pkg/os/doc.go

やってみまーす

**Comment by t-yuki** [comment]
パッケージドキュメントそのものはfile.goに書かれているように見えますね。
関数ごとの説明を書くなら別ですが・・・。

**Comment by atotto** [comment]
なにか不思議な構成ですね。
doc.goに実装が書かれているのはなにか意味があるんでしょうか。。

**Comment by ucho** [comment]
doc.goを削除し、file.goを追加するようにしようと思います。
また、file.goには多数のvar, const, funcの定義がありますが、これらを削除してパッケージコメントだけにしようかと思っています。理由は以下です。
- 他のファイルへの依存があり、パッケージ下のファイルをほぼ全て追加しなければならない
- buildタグを使った環境の場合分けがされており、環境によってうまくビルドできないかもしれない

みなさまのご意見もいただきたいです。

**Comment by atotto** [comment]
根本解決しておきたいですね。
なにか背景があるのかもしれませんが、doc.goに実装があるのはいけてないですよね・・

**Comment by inatus** [comment]
ご対応ありがとうございました。
