### ISSUE TITLE
robots.txt を修正しようと思います

### ISSUE THREAD

**Issue by atotto** [gophersjp/go#56]
http://golang-jp.org/robots.txt はデフォルトのままなので:

```
User-agent: *
Disallow: /
```

となってます。このままだと検索に引っかからないので
本家の http://golang.org/robots.txt ：

```
User-agent: *
Disallow: /search
```

と同じように設定しようかなと思います。この修正で懸念されるようなことってありますかね・・

**Comment by inatus** [comment]
ぜんぜん詳しくないのでまともにアドバイスできないのですが、後は以下を入れるか入れないかでしょうか...

Disallow: /status

**Comment by atotto** [comment]
statusは外してもよさそうですね。
本家と同じコンテンツがクロールされるのはあまり良くないと思いますので以下のようにしてみようかと思います：

```
User-agent: *
Disallow: /search

Disallow: /status/
Disallow: /*.go$
Disallow: /api/
Disallow: /include/
Disallow: /lib/
Disallow: /src/
Disallow: /test/
```

**Comment by inatus** [comment]
なるほど、そうですね。
よろしくお願いします。

**Comment by atotto** [comment]
修正完了しました。
http://golang-jp.org/robots.txt

ついでにサイトのgoのビルドバージョンをgo1.3にしておきました。

**Comment by atotto** [comment]
本件closeします。
