### ISSUE TITLE
Translation:./cmd/5*/doc.go

### ISSUE THREAD

**Issue by ryochack** [gophersjp/go#6]
5a: https://code.google.com/p/go/source/browse/src/cmd/5a/doc.go?r=3633a89bb56d
5c: https://code.google.com/p/go/source/browse/src/cmd/5c/doc.go?r=3633a89bb56d
5g: https://code.google.com/p/go/source/browse/src/cmd/5g/doc.go?r=3633a89bb56d
5l: https://code.google.com/p/go/source/browse/src/cmd/5l/doc.go?r=3633a89bb56d
の翻訳を追加しました。

`// +build ignore`
を消さないと、http://godoc.org/ には反映されない？

**Comment by atotto** [comment]
消さないとでません！
この調子で6,8とかもやっちゃってくださいな。

**Comment by ryochack** [comment]
ありがとうございます。修正しておきます。
6,8もついでにやっちゃいます。

**Comment by ryochack** [comment]
resolved @3f0bbd47a4193ef20d70eb52fcaeb2ca1e8b2b4c
