### ISSUE TITLE
Translation:./src/cmd/6*/doc.go and ./src/cmd/8*/doc.go

### ISSUE THREAD

**Issue by ryochack** [gophersjp/go#7]
386とamd64のgcツールについての翻訳を追加しました。
4f13782ab58cb3c2c3bfae29ccbef932fe0e01cf

**Comment by atotto** [comment]
5,6,8の翻訳したものを全部UTF-8にしてくださいな。
でないと godoc.org 上に表示されません。。

**Comment by ryochack** [comment]
今気づいて作業中でした。修正します。

**Comment by atotto** [comment]
らじゃっす！

**Comment by ryochack** [comment]
あれ？まだダメですかね？ 450eb8f9cbfe2df163d0d566a89118c12c9a45db
http://godoc.org/github.com/gophersjp/go

**Comment by ryochack** [comment]
反映されたのでCloseします。
