### ISSUE TITLE
translate.html の non-translated item リンク切れ

### ISSUE THREAD

**Issue by equal-l2** [gophersjp/go#78]
はじめまして。

翻訳に興味があって http://golang-jp.org/status/translate.html を覗いてみたのですが、 non-translated itemのファイルへのリンクがすべて https://github.com/golang/go へリダイレクトされていました。

修正の依頼はこちらのIssueでよろしいでしょうか?

**Comment by equal-l2** [comment]
PRありました
#77

**Comment by atotto** [comment]
ありがとうございます。そうですね…。変更がはやく、うまく回らなくなって、いったんリセットしたいなと思っているところですm(_ _)m
