### ISSUE TITLE
Translation: ./src/cmd/fix/doc.go

### ISSUE THREAD

**Issue by ryochack** [gophersjp/go#8]
始めます。
https://code.google.com/p/go/source/browse/src/cmd/fix/doc.go

**Comment by ryochack** [comment]
`// FIXME` のあたりの訳の意味が通じていないため、途中です。
どなたかレビューをお願いできないでしょうか？

**Comment by masato-ka** [comment]
メンバーの中でinatusが一番英語スキル高いと思うので、inutusさんレビューできないでしょうか？

**Comment by inatus** [comment]
では私がレビューします。

**Comment by inatus** [comment]
レビュー完了しました。issue/8という名前でブランチを切って修正したドキュメントをコミットしています。問題なければmasterにmergeして下さい。

ちなみに、2つめのFIXMEは意味としては、コマンドラインのヘルプに適用される修正のリストを表示する、ということなのでryochackさんの訳で問題無いと思います。実際に、go tool fix -?と打てばヘルプにAvailable rewrites are:という形で修正リストが表示されます。

**Comment by ryochack** [comment]
ありがとうございます！
１つ目のFIXMEは”全部、もしくは一部の”でよかったんですね。

issue/8ブランチをマージ後、削除しました。
